## Для чего он нужен

- Тип задач
	1. Генерация датасета для задач NLP 
- Особенности
	- Имеется различная локализация
	- Можно генерировать 
		1. персональные данные
		2. Документы
		3. Адреса и контакты
		4. Финансовые данные (номера карт, названия банков и тд)
		5. Транзакции и цены
		6. Бизнес данные (названия компаний, сферы, отрасли)
		7. Интернет домены, ip-адреса, пароли и тд

In [38]:
from faker import Faker
import pandas as pd

In [ ]:
# С локализацией (русские данные)
fake = Faker("ru_RU")

# С несколькими провайдерами
fake = Faker()
fake.add_provider("faker.providers.person.ru_RU")
fake.add_provider("faker.providers.address.ru_RU")

## Локализация

In [ ]:
fake_en = Faker("en_US")
fake_ru = Faker("ru_RU")

In [ ]:
def gen_personal_data(faker: Faker, loc="en") -> pd.DataFrame:
    if loc == "ru":
        person = [
            {
                "full_name": faker.name(),
                "first_name": faker.first_name(),
                "last_name": faker.last_name(),
                "middle_name": faker.middle_name(),
                "gender": faker.random_element(["M", "F"]),
                "age": faker.random_int(18, 90),
                "birthdate": faker.date_of_birth(minimum_age=18, maximum_age=90),
            }
            for i in range(10)
        ]
    else:
        person = [
            {
                "full_name": faker.name(),
                "first_name": faker.first_name(),
                "last_name": faker.last_name(),
                "gender": faker.random_element(["M", "F"]),
                "age": faker.random_int(18, 90),
                "birthdate": faker.date_of_birth(minimum_age=18, maximum_age=90),
            }
            for i in range(10)
        ]
    return pd.DataFrame(person)

In [42]:
display(gen_personal_data(fake_ru, loc="ru"))

,full_name,first_name,last_name,middle_name,gender,age,birthdate
0,Орехов Прокофий Феофанович,Александр,Семенов,Венедиктович,F,51,1947-05-07
1,Евдоким Юльевич Горшков,Наум,Блохина,Демидович,F,32,1982-09-14
2,Фока Августович Субботин,Лариса,Панов,Германович,M,49,1939-09-22
3,Александра Ниловна Родионова,Творимир,Копылов,Феликсович,F,48,1952-11-10
4,Вышеслав Харлампович Гурьев,Алла,Игнатов,Геннадиевич,F,53,1936-04-29
5,Азарий Исидорович Петров,Юлия,Андреев,Исидорович,M,24,1949-01-10
6,Белов Алексей Евстигнеевич,Доброслав,Фомичева,Афанасьевич,F,63,1977-10-03
7,Дьячкова Людмила Георгиевна,Антонина,Овчинникова,Романовна,F,23,2006-09-04
8,Киселев Мокей Архипович,Клавдий,Фомичева,Фомич,F,71,1985-04-30
9,Савельев Леонид Антипович,Бажен,Котов,Рубеновна,F,72,1949-11-09

In [43]:
display(gen_personal_data(fake_en))

          full_name first_name last_name gender  age   birthdate
0        Sheri Bond       Dawn    Hanson      F   81  1937-10-18
1        Sarah Reed     Alicia  Gonzalez      F   50  1976-04-07
2   Anthony Stevens     Angela    Stokes      F   38  1997-01-11
3  Mary Jackson DDS   Kimberly   Padilla      M   88  1939-06-05
4      Fred Johnson   Danielle   Nichols      M   23  1982-04-28
5      Steven Moore      Shari    Taylor      F   89  1969-03-08
6   Tracy Hernandez    Jeffrey  Whitaker      M   80  1988-02-12
7         Tyler Lam      Jason       Lee      M   83  1996-12-01
8       Nicole Ford     Austin  Martinez      F   60  1945-03-28
9   Clayton Pollard   Kimberly    Wilson      F   40  1969-11-21

## Банкинг

In [ ]:
def gen_bank_data(faker: Faker) -> pd.DataFrame:
    data = [
        {
            "credit_card": faker.credit_card_number(),
            "card_expire": faker.credit_card_expire(),
            "cvv": faker.credit_card_security_code(),
            "card_provider": faker.credit_card_provider(),
            "bank": faker.bank(),
            "bic": faker.bic(),
            "account": faker.bban(),
        }
        for i in range(10)
    ]

    return pd.DataFrame(data)

In [50]:
display(gen_bank_data(fake_ru))

,credit_card,card_expire,cvv,card_provider,bank,bic,account
0,6788989262069148,01/31,413,МИР,ВРБ,041800692,WBUX3221116304455
1,6581652998196564,07/32,510,Mastercard,Московское Ипотечное Агентство,049946076,OVZT3151309946050
2,376009505019205,09/26,388,American Express,НИБ,041899077,AQNA7626198104179
3,6168621172067041,11/28,661,МИР,Банк 131,041260902,TIDV3461620973826
4,2323170505768868,01/32,177,Union Pay,Роскосмосбанк,047605062,VUFJ4427364521273
5,8113264675179781,08/34,022,МИР,Банк ЧБРР,045635497,PJTR5001861944889
6,346105047992466,03/27,465,Maestro,Роскосмосбанк,044662388,DVRF5862870115242
7,375033039008931,06/26,566,Union Pay,РБА,047508400,VHMG5384949054311
8,6918362878064627,06/30,276,American Express,Элита,045479076,CMCY0158707737589
9,6019967170878884,11/26,375,МИР,Дон-Тексбанк,048776133,VMAB3771716445660

In [51]:
display(gen_bank_data(fake_en))

AttributeError: The Provider provider does not have a 'banks' attribute. Consider contributing to the project and  adding a 'banks' tuple to enable bank name generation.

## Бизнес и компании

In [ ]:
def gen_business_data(faker: Faker) -> pd.DataFrame:
    data = [
        {
            "company": faker.company(),
            "company_suffix": faker.company_suffix(),
            "catch_phrase": faker.catch_phrase(),
            "bs": faker.bs(),
            "job": faker.job(),
            "industry": faker.random_element(["IT", "Маркетинг", "Финансы", "Розница"]),
        }
        for i in range(10)
    ]

    return pd.DataFrame(data)

In [60]:
display(gen_business_data(fake_ru))

,company,company_suffix,catch_phrase,bs,job,industry
0,ИП «Анисимов»,Инкорпорэйтед,Качественный и клиент-серверный искусственный ...,Эксплуатация прозрачных архитектур,Астроном,IT
1,ОАО «Назаров»,Лимитед,Открытый и потенциальный параллелизм,Продление корпоративных технологий,Дизайнер,Розница
2,АО «Пестова»,Инкорпорэйтед,Общедоступная и веб-ориентированная реализация,Использование открытых сетей,Авиационный техник,IT
3,ЗАО «Ковалева»,Лимитед,Клиент-ориентированная и нейтральная фокус-группа,Монетизация прозрачных взаимодействий,Начальник военного оркестра,Розница
4,РАО «Борисова-Горбачев»,и партнеры,Горизонтальная и веб-ориентированная нейронная...,Включение беспроводных диапазонов,Виноградарь,Маркетинг
5,АО «Смирнова Суворова»,Инк,Делегируемая и составная проекция,Ускорение интегрированных интерфейсов,Математик,IT
6,АО «Моисеев-Михайлова»,Лимитед,Элегантная и мультимедийная база данных,Разворачивание сенсационных ниш,Садовник,IT
7,X5 Retail Group,Инкорпорэйтед,Объектная и переходная база данных,Увеличение подробных инфраструктур,Дефектолог,Финансы
8,ЗАО «Самсонов Игнатов»,Лимитед,Органичная и мобильная инфраструктура,Мотивация расширяемых рынков,Египтолог,Финансы
9,ФК Пульс,Лтд,Синхронизированный и широкий адаптер,Модернизация активных взаимодействий,Плотник,Розница

## Интернет

In [ ]:
def gen_internet_data(faker: Faker) -> pd.DataFrame:
    data = [
        {
            "url": faker.url(),
            "domain": faker.domain_name(),
            "ipv4": faker.ipv4(),
            "ipv6": faker.ipv6(),
            "mac_address": faker.mac_address(),
            "user_agent": faker.user_agent(),
            "username": faker.user_name(),
            "password": faker.password(length=12),
        }
        for i in range(10)
    ]

    return pd.DataFrame(data)

In [63]:
display(gen_internet_data(fake_ru))

,url,domain,ipv4,ipv6,mac_address,user_agent,username,password
0,https://rozhkova.net/,oao.com,88.116.233.168,6bc2:fd74:da5f:bc2f:4560:5a7a:96b2:f37,9a:79:04:a1:42:33,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_0...,makar_95,I44Mot6YJ@!O
1,http://npo.biz/,zao.org,19.42.40.218,4bdc:cb20:32a8:a91a:fbd2:cac2:5d43:ccb9,dc:c9:bf:db:b8:f1,Opera/8.30.(Windows 98; Win 9x 4.90; pap-CW) P...,budimirkuzmin,1)K_vY_w%yMj
2,https://yuzhuralzoloto.org/,zao.info,153.96.130.255,1bc8:ef8c:9338:da54:9699:5ad2:bb30:56b8,ee:06:13:f0:7e:17,Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit...,qfedotov,)RlE9PBct5Xa
3,http://ao.edu/,rao.com,130.26.186.54,4314:108b:7358:2f2f:23f4:b768:8850:e1c5,74:7d:89:2b:d6:6e,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_3 like M...,baranovlukjan,IqX80XJs^Pa&
4,http://tarkett.biz/,zao.edu,13.140.68.104,f96a:e492:be45:9b0:7e01:c769:f85c:27e,ee:c4:36:93:95:f8,Mozilla/5.0 (Linux; Android 2.3.6) AppleWebKit...,gordeevapollon,+(7iMm(uK%Mz
5,https://zao.ru/,ip.ru,104.224.227.34,7293:cd8a:b4b5:f49d:75c8:fa84:ce1e:75c6,68:53:5e:09:d7:89,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_4...,valerija2016,SQ1)7JlbWdB%
6,https://npo.org/,oao.edu,51.6.150.255,4506:5d7:2eb6:c815:f5be:19be:eef0:4243,1e:35:fb:83:9c:e1,Opera/8.52.(Windows NT 10.0; gl-ES) Presto/2.9...,fedorovkuprijan,3zQuRM$1!ef$
7,https://www.severni.org/,suvorov.biz,95.6.159.171,9d05:3942:15c2:7542:7e62:b431:d929:5cc4,40:fc:f1:d3:94:8f,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_7_8...,aartemeva,9e$l9Ns0j9!4
8,https://rao.net/,ooo.org,77.179.183.226,b0c9:3ed6:832b:eaca:c206:56cd:fb3e:dc9b,16:26:a8:c0:bc:fc,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_1 like M...,matve28,C_M+u6yp256o
9,http://www.npo.biz/,ao.info,133.122.97.138,225:7296:30f6:da2b:448:7789:800a:9b69,0c:f6:99:69:06:76,Mozilla/5.0 (Windows NT 5.2; tg-TJ; rv:1.9.1.2...,hariton_50,7KRHdY+E*nG%

In [64]:
display(gen_internet_data(fake_en))

,url,domain,ipv4,ipv6,mac_address,user_agent,username,password
0,http://www.schwartz.com/,lyons.com,3.13.86.243,deef:6552:d33b:f821:c670:9454:103c:a597,04:20:61:86:5c:b6,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) G...,sancheznatalie,Ep28B2CqG&)T
1,http://hanson.com/,york.com,50.67.80.41,2773:fba2:2ed1:2eb4:1bd2:9973:1ccb:1798,ce:61:cb:3e:7f:59,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,arianahull,I9z#!^Gp!G*U
2,https://www.brock-silva.biz/,thomas.com,146.27.29.215,a7bf:a5ee:90a:349a:5985:84e:99d5:bdc4,ac:f5:8b:12:e1:f8,Mozilla/5.0 (Android 7.1.2; Mobile; rv:10.0) G...,jacobsmicheal,T*5wSfU(XI+L
3,https://smith.com/,wang.com,2.158.180.78,98f8:4259:1e48:4ff0:9d55:c460:1ff4:b1e3,22:ea:70:6a:59:a6,Opera/8.37.(X11; Linux i686; ne-NP) Presto/2.9...,ghenry,32_o)jvvtU6P
4,http://mooney-sampson.com/,mcdonald.info,160.248.151.152,5df8:b5f6:963b:bb85:9bed:f885:ea09:f5e3,60:72:af:c3:05:0c,Mozilla/5.0 (Windows; U; Windows 95) AppleWebK...,ashleybaker,8w%Gw)rCR70R
5,https://williams.com/,mcpherson.com,146.69.226.41,ad30:fb4e:3184:3c0:4716:8c5a:8088:7afa,d4:83:2f:aa:9d:4d,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_12_2; ...,bishopsteve,g7+FhDSmxs#@
6,http://www.baker.com/,parker.com,73.88.224.88,13d5:f444:9c8f:ec6a:bca2:b527:dea5:1410,b6:6b:ec:3f:fd:2f,Mozilla/5.0 (Linux; Android 2.3.5) AppleWebKit...,holly26,APQGEHKof^7B
7,http://lane-jones.biz/,lopez.com,178.102.132.115,da4e:1abd:e403:7799:c4f4:d4fb:580a:a74f,68:1b:5b:36:57:53,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,thomas46,a_2FkmuiBgA&
8,https://www.cooper-wilkinson.info/,cook.info,123.202.121.156,5616:887a:ec30:87e8:abdf:86cd:e271:6ea7,b6:30:d6:4a:a2:d5,Mozilla/5.0 (iPad; CPU iPad OS 11_4_1 like Mac...,gallegosjustin,@7EOBdRM*JTI
9,http://www.dawson-gardner.com/,davis.info,23.140.7.251,5bb0:da92:a092:525f:5c1d:904e:e75d:16de,b4:03:96:81:e7:ac,Mozilla/5.0 (iPhone; CPU iPhone OS 16_7_6 like...,vbrown,)wcs%JZ*AZQ0